# testing
name: test sheets

on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: googlesheet_actions
        uses: rjoydip/googlesheet-actions@0.1.1
        with:
          sheet-id: 1NdrCTFzbeqN-nvlLzy8YbeBbNwPnHruIe95Q1eE4Iyk
      - id: echo
        uses: actions/github-script@v6
        with:
          script: |
              console.log(${{steps.googlesheet_actions.outputs.result}})
