# testing
name: test sheets

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - id: checkout
        uses: actions/checkout@v3
      - id: googlesheet_actions
        uses: enstars/googlesheet-actions@master
        with:
          sheet-id: 1NdrCTFzbeqN-nvlLzy8YbeBbNwPnHruIe95Q1eE4Iyk
          path: ja/cards-test.json
      - id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: auto-sync-${{ steps.date.outputs.date }}
